sqs:
  url: https://sqs.us-east-1.amazonaws.com/890742596725/test-queue

s3:
  bucket: "pcw-test"  
  region: "us-east-1"
  endpoint: "https://us-east-1.linodeobjects.com"

mongo:
  uri: "mongodb+srv://yeomdennis:<PASSWORD>@bat-computer.e7yar.mongodb.net/?retryWrites=true&w=majority&appName=bat-computer"
  dbName: "bat-computer"

redis:
  port: 6380